services:
  - type: web
    name: frame-caption
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers=1 --threads=1 --timeout=300 --preload